/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Image: typeof import('./src/components/Image/index.vue')['default']
  }
}
